services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  catalog:
    build:
      context: catalog   # El Dockerfile de catalog hace COPY requirements.txt / main.py (sin prefijo)
      dockerfile: Dockerfile
    image: marketplace/catalog:v1
    container_name: catalog
    ports:
      - "8001:8000"   # REST: /health /products /reserve /metrics
      - "50051:50051" # gRPC: CheckStock
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy

  orders:
    build:
      context: orders    # El Dockerfile de orders hace COPY requirements.txt / main.py (sin prefijo)
      dockerfile: Dockerfile
    image: marketplace/orders:v1
    container_name: orders
    ports:
      - "8000:8000"
    environment:
      CATALOG_GRPC_ADDR: catalog:50051
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
      catalog:
        condition: service_healthy

  notifications:
    build:
      context: notifications  # El Dockerfile de notifications hace COPY requirements.txt / worker.py (sin prefijo)
      dockerfile: Dockerfile
    image: marketplace/notifications:v1
    container_name: notifications
    environment:
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy


  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    depends_on:
      - catalog

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus